### ISSUE TITLE
火狐浏览器无法使用本脚本

### ISSUE THREAD

**Issue by NopantsNobra** [liuyubing233/zhihu-custom#82]
无法打开首页（能看到内容然后瞬间刷新报错），和设置无关，重新安装脚本或恢复默认设置也无法解决问题。
![屏幕截图 2023-12-21 012814](https://github.com/liuyubing233/zhihu-custom/assets/70736734/22a1a27b-bed1-4873-af11-5c1d8aa5fa89)

个人主页显示错误
![圖片](https://github.com/liuyubing233/zhihu-custom/assets/70736734/3d6a1828-dc50-42ad-a33e-4441c1b43e19)

已打开回答详情页可以浏览，但无法加载其他回答。
![圖片](https://github.com/liuyubing233/zhihu-custom/assets/70736734/6d6b31c1-e1be-40b0-8fb2-046626d39ea6)

刷新报错“草稿加载失败”。
![圖片](https://github.com/liuyubing233/zhihu-custom/assets/70736734/52f4d450-1773-4772-a172-9f1eda0daa85)

和其他插件无关，经反复尝试，仅在开启本脚本时网页崩溃（另一个“极简知乎”脚本就可以正常使用）。

**Comment by NopantsNobra** [comment]
问题出现约1周时间，曾经也有过类似问题后来随着更新消失了。

**Comment by NopantsNobra** [comment]
问题解决，火狐浏览器更新了。

**Comment by liuyubing233** [comment]
看一下最新版本（4.9.1）有没有解决这个问题

**Comment by NopantsNobra** [comment]
并没有解决。
昨天关闭问题是因为更新了火狐浏览器的版本（121.0 64 位），然后突然就好了，直到深夜都没有任何问题，因为在chorme上使用是正常的，所以认为是浏览器自身问题。但是今天火狐再打开新页面复现了上面问题，所以重新打开了issue。

**Comment by liuyubing233** [comment]
配置可以发给我看一下吗，在「配置操作」可以直接导出配置

**Comment by liuyubing233** [comment]
> 配置可以发给我看一下吗，在「配置操作」可以直接导出配置

获取按F12打开控制台看看有没有红色的报错（ ChunkLoadError: Loading chunk 1057 failed. 除外）

**Comment by NopantsNobra** [comment]
配置如下：
[知乎编辑器配置-1703242043585.txt](https://github.com/liuyubing233/zhihu-custom/files/13751656/-1703242043585.txt)

F12控制台错误略多：
![圖片](https://github.com/liuyubing233/zhihu-custom/assets/70736734/87d83c0a-1780-4a13-9d8e-797208dc53f3)
![圖片](https://github.com/liuyubing233/zhihu-custom/assets/70736734/7fb810ea-2c57-470a-80d0-15ca59fbf15d)
![圖片](https://github.com/liuyubing233/zhihu-custom/assets/70736734/a9fc0190-e4f7-4aba-a318-70faafec839b)
![圖片](https://github.com/liuyubing233/zhihu-custom/assets/70736734/4f6287b4-ad7f-4f51-b9ee-65fc9dead863)

**Comment by liuyubing233** [comment]
![image](https://github.com/liuyubing233/zhihu-custom/assets/33803840/53e74cb8-e532-4377-8e88-611e3587acc8)
4.11.0 尝试关闭下接口拦截功能吧，看这像是浏览器阻断了接口拦截的功能

**Comment by NopantsNobra** [comment]
Good job buddy, it's done.
